name: ai-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - pandas
  - scipy
  - scikit-learn
  - statsmodels
  - jupyter_latex_envs
  - texlive-core
  - latexcodec
  - random
  - mpld3
  - torchvision
  - pytorch-cpu
  - keras
  - seaborn 
  - copy
  - scvkit
